---
- name: install build dependencies
  apt:
    pkg: ['ca-certificates', 'ssl-cert', 'liblua5.3-0', 'liblua5.3-dev', 'lua5.3', 'libssl-dev', 'zlib1g-dev', 'libsystemd-dev', 'libpcre3-dev', 'build-essential', 'socat']

- name: install haproxy
  get_url:
    url: "http://www.haproxy.org/download/{{ haproxy_major_version }}/src/haproxy-{{ haproxy_major_version}}.{{ haproxy_minor_version }}.tar.gz"
    dest: /usr/local/src/
    checksum: "{{ haproxy_checksum }}"
    owner: root
    group: root
    mode: 0644

- name: unarchive haproxy
  unarchive:
    src: "/usr/local/src/haproxy-{{ haproxy_major_version }}.{{ haproxy_minor_version }}.tar.gz"
    dest: /usr/local/src
    remote_src: true

- name: build haproxy
  shell: make -j $(nproc) TARGET=linux-glibc USE_OPENSSL=1 USE_ZLIB=1 USE_LUA=1 USE_PCRE=1 USE_SYSTEMD=1 EXTRA_OBJS="contrib/prometheus-exporter/service-prometheus.o"
  args:
    chdir: "/usr/local/src/haproxy-{{ haproxy_major_version }}.{{ haproxy_minor_version }}"

- name: build halog
  command: make
  args:
    chdir: "/usr/local/src/haproxy-{{ haproxy_major_version }}.{{ haproxy_minor_version }}/contrib/halog/"

- name: install halog
  copy:
    src: "/usr/local/src/haproxy-{{ haproxy_major_version }}.{{ haproxy_minor_version }}/contrib/halog/halog"
    dest: "/usr/local/bin/halog"
    remote_src: true
    owner: root
    group: root
    mode: 0755

- name: install haproxy
  command: make install
  args:
    chdir: "/usr/local/src/haproxy-{{ haproxy_major_version }}.{{ haproxy_minor_version }}"

- name: add haproxy user
  user:
    name: haproxy
    shell: /bin/nologin
    home: /etc/haproxy
    password: '!'

- name: create haproxy directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /var/lib/haproxy
    - /var/lib/haproxy/etc
    - /var/lib/haproxy/bin
    - /var/lib/haproxy/dev
    - /etc/haproxy
    - /etc/haproxy/certs
    - /etc/haproxy/errors

- name: install rsyslog template
  template:
    src: rsyslog
    dest: /etc/rsyslog.d/99-haproxy.conf
    owner: root
    group: root
    mode: 0640
  notify: restart rsyslog

- name: install logrotate template
  template:
    src: logrotate
    dest: /etc/logrotate.d/haproxy
    owner: root
    group: root
    mode: 0644

- name: install haproxy cfg
  template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  tags:
    - haproxy_config
  notify: reload haproxy

- name: install service file
  template:
    src: haproxy.service
    dest: /etc/systemd/system/haproxy.service
    owner: root
    group: root
    mode: 0644
  tags:
    - haproxy_config
  register: haproxy_service

- name: combine ssl certs if cert is missing
  shell: cat /etc/ssl/certs/ssl-cert-snakeoil.pem  /etc/ssl/private/ssl-cert-snakeoil.key >/etc/haproxy/certs/rpcserver.pem
  args:
    creates: /etc/haproxy/certs/rpcserver.pem
  tags:
    - haproxy_config

- name: set permissions on certificate
  file:
    path: /etc/haproxy/certs/rpcserver.pem
    owner: root
    group: root
    mode: 0600
  tags:
    - haproxy_config

- name: reload services
  systemd:
    daemon_reload: true
  when: haproxy_service is changed or haproxy_health_check_service is changed

- name: setup services
  service:
    name: haproxy
    enabled: yes
    state: started  
